Add git config setting to allow commit to master
Tweak the pre-commit hook so that if 'hooks.committomaster' is set to
true then if won't complain.

diff --git a/config/git/hooks/pre-commit b/config/git/hooks/pre-commit
--- a/config/git/hooks/pre-commit
+++ b/config/git/hooks/pre-commit
@@ -1,9 +1,13 @@
 #! /bin/sh
 
-# pre-commit: fail if current branch is master
-case "$(git rev-parse --abbrev-ref HEAD)" in
-master) echo "you forgot to make a branch!" 1>&2; exit 1;;
-esac
+allowcommittomaster=$(git config --bool hooks.allowcommittomaster)
+
+if [ "$allowcommittomaster" != "true" ]; then
+  # pre-commit: fail if current branch is master
+  case "$(git rev-parse --abbrev-ref HEAD)" in
+  master) echo "you forgot to make a branch!" 1>&2; exit 1;;
+  esac
+fi
 
 # execute the repo hooks
 if [ -x $GIT_DIR/hooks/pre-commit ]; then
